"""adding user_id to review model

Revision ID: 800705cb1167
Revises: b9e3f49864ef
Create Date: 2023-09-01 12:21:44.435155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800705cb1167'
down_revision = 'b9e3f49864ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
