"""adding user_id to review model

Revision ID: dd26d6f514a2
Revises: 800705cb1167
Create Date: 2023-09-01 12:27:00.881952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd26d6f514a2'
down_revision = '800705cb1167'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
